# Development Stage
FROM node:20 AS development

WORKDIR /usr/app

COPY package*.json ./

# Install both runtime and development dependencies
RUN yarn

COPY start_next_clear .

EXPOSE 3000

ENV PORT 3000

# Docker listen 0.0.0.0 so it is very important to set the host like this
ENV HOSTNAME "0.0.0.0"

CMD ["yarn", "dev"]